logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia_db
    username: nnpUser
    password: nnpPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # for testing
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect