server:
  servlet:
    context-path: "/api"
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
    com.aeiouxx.semestralniprace: TRACE
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia_db
    username: nnpUser
    password: nnpPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect